default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  database: <%= ENV.fetch('POSTGRES_DATABASE') %>
  username: <%= ENV.fetch('POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default