default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  host:     <%= ENV.fetch('POSTGRESS_HOST', 'localhost') %>
  database: <%= ENV.fetch('POSTGRESS_DATABASE') %>
  username: <%= ENV.fetch('POSTGRESS_USER') %>
  password: <%= ENV.fetch('POSTGRESS_PASSWORD') %>
  
test:
  <<: *default

development:
  <<: *default

deploy_dev:
  <<: *default

staging:
  <<: *default

production:
  <<: *default